version: 0.2

env:
    variables:
        NODE_ENV: "production"

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - npm install -g react-scripts
    pre_build:
        commands:
            - npm install
    build:
        commands:
            npm run build
artifacts:
    type: zip
    files:
        - '**/*'
    discard-paths: no
    base-directory: build
cache:
    paths:
        - './node_modules/**/*'